"""caching of avatar hashes

Revision ID: 35758164ea18
Revises: f614102ecf0d
Create Date: 2020-02-01 18:54:11.408774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35758164ea18'
down_revision = 'f614102ecf0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
