"""rich text posts

Revision ID: 49020c9f5e8f
Revises: 903c42f59543
Create Date: 2020-02-03 02:27:51.510586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49020c9f5e8f'
down_revision = '903c42f59543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
